name: Build
on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set FW version
        id: set-fw-version
        run: |
          echo "FW_VER=0.0.5" >> $GITHUB_OUTPUT

      - name: Release folder
        run: |
          mkdir nordic_${{ steps.set-fw-version.outputs.FW_VER }}
          cp -r sample_art nordic_${{ steps.set-fw-version.outputs.FW_VER }}
          ls -la


      - name: Upload Firmware release artifact
        uses: actions/upload-artifact@v3
        with:
          name: nordic_${{ steps.set-fw-version.outputs.FW_VER }}
          path: nordic_${{ steps.set-fw-version.outputs.FW_VER }}
          if-no-files-found: error

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v3

      - name: Print fw ver
        run: |
          echo "${{ steps.set-fw-version.outputs.FW_VER }}"

      - name: Release
        uses: softprops/action-gh-release@v1

        with:
          files: |
            ev_nordic_${{ steps.set-fw-version.outputs.FW_VER }}/*
